apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-browser-backend
  labels:
    app: {{ $.Release.Name }}-browser-backend
spec:
  selector:
    app: {{ $.Release.Name }}-browser-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
