# Ingress - Expose the application externally
# This routes external traffic to the frontend, which proxies /api to backend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-browser-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "{{ printf "%t" $.Values.browser.frontend.forceSslRedirect }}"
spec:
  ingressClassName: {{ $.Values.browser.frontend.ingressClassName }}
  rules:
    - host: {{ $.Values.browser.frontend.host }}
      http:
        paths:
          - path: {{ $.Values.browser.frontend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-browser-frontend
                port:
                  name: http
