apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-browser-frontend
  labels:
    app: {{ $.Release.Name }}-browser-frontend
spec:
  selector:
    app: {{ $.Release.Name }}-browser-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
