# Kustomization file for backend deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-ajjxp

commonLabels:
  project: aql
  team: swep

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
